import type { Metadata } from 'next';
import { Quicksand } from 'next/font/google';
import './globals.css';
import Sidebar from '@/components/sidebar';
const quickSand = Quicksand({ subsets: ['latin'] });
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import 'react-data-grid/lib/styles.css';
import 'rsuite-table/dist/css/rsuite-table.css';
import SessionWrapper from '@/components/sessionWrapper';
// import useInternetConnection from '@/utils/hooks/useInternet';
// import ping from 'ping';
// import OfflinePage from '../components/offlinePage';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pingResult = await ping.promise.probe('www.google.com');
  // const pathname = headers().get('x-next-pathname') || '/signIn';

  return (
    <SessionWrapper>
      <html lang='en'>
        <body className={quickSand.className}>
          <div className='flex min-h-screen w-full'>
            <Sidebar />
            <main className='flex-1 overflow-x-hidden p-4'>{children}</main>
            <ToastContainer />
          </div>
        </body>
      </html>
    </SessionWrapper>
  );
}
